/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.myvivanx.myvivanxcalculator;

public final class R {
    public static final class anim {
        public static final int scale_up=0x7f040000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int colorAccent=0x7f050002;
        public static final int colorControlHighlight=0x7f050003;
        public static final int colorControlNormal=0x7f050004;
        public static final int colorPrimary=0x7f050000;
        public static final int colorPrimaryDark=0x7f050001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int neon_btn=0x7f020001;
        public static final int neon_operator=0x7f020002;
    }
    public static final class id {
        public static final int btn0=0x7f080005;
        public static final int btnClear=0x7f080003;
        public static final int btnDivide=0x7f080004;
        public static final int btnEqual=0x7f080006;
        public static final int tvBranding=0x7f080000;
        public static final int tvHistory=0x7f080001;
        public static final int tvMain=0x7f080002;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
    }
    public static final class style {
        public static final int AppTheme=0x7f070000;
    }
}
